### ISSUE TITLE
[Candidate 2v2 District 10 ZH v5] Units can drive and shoot through Oil Derricks

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#287]
**Issue Description**
Units can drive and shoot through Oil Derricks.

**Expected behavior**
Units can not drive and shoot through Oil Derricks

**Screenshots**

![shot_20230928_111958_47](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ea6d9063-4a23-4abf-8247-64f7439f50a3)

**Comment by Jundiyy** [comment]
Perhaps the map uses scripts to place Oils. Any other building will also allow units to move through and shoot non projectiles through them.

**Comment by toirehantaa** [comment]
if the bottom oil was the only one that was able to be driven through, then the bug is fixed

**Comment by xezon** [comment]
Not fixed.

![shot_20230929_164740_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/82c2ba32-b7c6-44e5-a823-96b872050b88)

![shot_20230929_164751_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c4bf9067-8a5e-412a-98e5-0ab2fd200f90)

**Comment by toirehantaa** [comment]
hmm... that is weird, those oils are preplaced - maybe it is due to the water being originally there before being lowered down

**Comment by xezon** [comment]
Map "Battleship Bay ZH v1" also has an Oil Derrick in a flood zone and there collision works normally. Perhaps check how it is setup there and try replicate it if applicable.

**Comment by toirehantaa** [comment]
Did not find any difference to the Oil in Battleship Bay. Made the ground beneath impassable to hotfix it. Works now as intended

**Comment by xezon** [comment]
This is not a good solution.

### Soldier can no longer capture the Oil Derrick

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2f2f190b-f453-4b09-b267-1314f463f81b

### Soldier has to move to specific spot at Oil Derrick and start capture. Vehicle cannot properly drive all around the Oil Derrick to try crush the soldiers.

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ad5399ed-1355-4dbf-b52a-93fce42e5c93

**Comment by xezon** [comment]
But I see Battleship Bay has done the same. I suggest make the impassable area smaller, so that units can comfortably approach the structure from all directions.

**Comment by toirehantaa** [comment]
fixed
