### ISSUE TITLE
[Candidate 2v2 Animals of the Generals ZH v1] Space and distance between Oil Derricks is very different

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#396]
## Observed behaviour

Space and distance between Oil Derricks is very different.

## Expected behavior

Space and distance between Oil Derricks is about the same.

## Screenshots

![shot_20231010_200331_39](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6ab7b2cd-3c80-4eb9-acf4-7eb4a3dc7324)

![shot_20231010_200352_40](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d332c8b4-7835-4d19-8a08-79af4d2b6631)

**Comment by TimberOwl** [comment]
nice catch but i gotta check is it equal distance to players if it is then it doesnt matter if 2 oils are close to gether but if one player can get quicker then the other than thats a balance issue yeah

**Comment by TimberOwl** [comment]
okay i fixed the distance between players to oils every spawn has same distance level to the oils . but the oil space betweeb them might look different but player distance is more important for balance

**Comment by xezon** [comment]
Not fixed.

![shot_20231015_114541_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/971657d9-63b8-4951-945a-f2ecb433e7fa)

![shot_20231015_114548_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1da7b6e2-e4bf-4cc0-be28-4cdc77fcce18)

**Comment by xezon** [comment]
Space is more equal now. But there appears to be inconsistency in how well the China Supply can be placed. East side still has a bit more room, which allows trucks to collect better when placed so:

![shot_20240121_180131_34](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f522e3f4-3891-4edf-b376-1e276c8477ee)

![shot_20240121_180154_35](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/555c5e4c-cac7-4a37-a7e7-e52a0e0e3eac)

Also, the Oil Derricks have moved and it looks like they are not placed on the same column.

![shot_20240121_180234_36](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/76b25ab0-b22d-45da-a289-52e92b9d218d)

![shot_20240121_180245_37](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/675bf192-1d68-4d19-996b-64bee7702ed8)

**Comment by TimberOwl** [comment]
my bad that i didnt thought about perfect supply ill fix it

**Comment by xezon** [comment]
Both sides now have enough space for China Supply build.

The Oil Derricks still look to be slightly differently positioned from one side to another. On the right side they are also rotated a bit off the 90 degrees angle step.

![shot_20240323_131619_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a50ab9a6-13ed-4594-b6e3-d16492c6c589)

![shot_20240323_131622_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2f89ec20-3d1e-4285-ab77-dc2579ba973f)

![shot_20240323_131803_14](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/cf85218a-f072-4537-96a9-ad89a2e85c1e)

![shot_20240323_131816_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e40dfb13-de07-4d57-90a7-92e0a9489c32)

**Comment by xezon** [comment]
Not 90 degrees (minor)

![shot_20240323_132216_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/495a1dff-1e6c-40b3-a6b3-fb287e860739)

**Comment by xezon** [comment]
There are now rocks that prevent Supply builds near the ocean. The Oil Derrick rotations have been fixed. The Oil Derrick positions appear to be unchanged. I think we can mark this as fixed.
