### ISSUE TITLE
[Candidate 2v2 Oil Carnage ZH v1] Oil Refineries have no symmetric alignments

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#406]
## Observed behaviour

Oil Refineries have no symmetric alignments.

## Expected behavior

All Oil Refineries have symmetric alignments.

## Screenshots

![shot_20231012_171053_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8c41e4aa-76a8-4f03-aea7-2ec2d2c63cc8)

![shot_20231012_171058_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/eb2d49b0-e7fd-49c5-b8f5-fd023690aebf)

![shot_20231012_171107_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/05e68d47-8b97-45b4-8b48-72b711034670)

**Comment by TimberOwl** [comment]
fixed

**Comment by TimberOwl** [comment]
dont forget the delete the older version

**Comment by xezon** [comment]
Top right one is still not symmetric. It's 3 small canisters should face map center. I think rotating by 90 degrees would change distance to Oil Derricks. So a rotation would have to be carefully considered.
