### ISSUE TITLE
[Candidate 3v3 Cursed Hollows ZH v1] Destructible barrels around mirrored Oil Refineries in center are not properly placed

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#449]
## Observed behavior

Destructible barrels around mirrored Oil Refineries in center are not properly placed

## Expected behavior

Destructible barrels around mirrored Tech Buildings are properly placed.

## Screenshots

![shot_20231118_123058_58](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f4c1cf09-0cfa-4048-9088-4810af29da42)

![shot_20231118_123114_59](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/517dc5f2-ceb5-4e2c-9e38-551ac5a76d29)

**Comment by TimberOwl** [comment]
fixed

**Comment by xezon** [comment]
Was changed, but not fixed. Barrels are not mirrored correctly. Neither is the rotation of the Tech building, which likely is the root of the problem.

**Comment by xezon** [comment]
Was changed again, but looks wrong. Oil barrels now face the same team on both sides.

**Comment by TimberOwl** [comment]
ok done
