### ISSUE TITLE
[Candidate 2v2 Spiders Island ZH v1] Map uses houses with missing fire ports

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#509]
## Observed behavior

Map uses houses with missing fire ports. Soldiers shoot from 0,0,0. Soldiers in these buildings consistently damage themselves.

## Expected behavior

Map uses houses with good fire port setups only or is setup in a way where those houses with broken fire ports do not cause problems.

## Screenshots

![shot_20231126_190806_49](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/81a87679-c857-4325-b764-91f266c7d591)

![shot_20231126_190814_50](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/fdf409b6-8ad5-4e47-a292-4d49a7047bc3)

**Comment by xezon** [comment]
Perhaps huts need to be elevated a bit above terrain. And terrain needs to be flat.

**Comment by NoMerciBKK** [comment]
fixed

**Comment by xezon** [comment]
Better. But is still an issue on the other side.

![shot_20231127_192646_14](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5c7a94fa-d58c-4078-b81d-2a1baccd36ac)

**Comment by xezon** [comment]
Houses are still self destructing when occupants shoot south. On both sides.

**Comment by NoMerciBKK** [comment]
updated
