### ISSUE TITLE
[Candidate 3v3 Medieval Era ZH v4] Outer Supply Piles have inconsistent building space

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#556]
## Observed behavior

Outer Supply Piles have inconsistent building space.

## Expected behavior

Mirrored Supply Piles offer equal building opportunities.

### Has no room

![shot_20231230_195009_64](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b863fe29-a519-4487-89af-84ddbaa16c72)

### Has decent room

![shot_20231230_195030_65](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/fb3c044e-9571-4053-8fe0-b58f6cb5c2e0)

### Has decent room

![shot_20231230_195055_66](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6eda2b4a-f8ba-4857-a2f8-2c496c73f8ed)

### Has no room

![shot_20231230_195105_67](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d6d9e6ea-5c09-4654-b054-43343fe41418)

### Has decent room

![shot_20231230_195127_68](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c2f105dd-cfd8-4fc7-8dd0-aa7404774c63)

### Has tight room

![shot_20231230_195146_69](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/34f3573d-0c59-477e-9855-4b87ef3da29f)

**Comment by toirehantaa** [comment]
fixed

**Comment by xezon** [comment]
GLA can now build supplies at all locations.

But China still cannot. The distances to the mountains are different.

![shot_20240118_203218_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2d8b4fd4-cebe-494d-a147-f9895961f2a3)

![shot_20240118_203231_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/eaf214fc-de7a-4ea1-b3fc-10bad7272f8a)

![shot_20240118_203248_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6cc772bd-fdba-46f0-ac4f-6357dc6128f3)

![shot_20240118_203301_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2e0c0da2-0e00-4393-894e-f4a26788b52d)

![shot_20240118_203312_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7a7fef52-d634-4e29-b9cd-90a195e219ea)

![shot_20240118_203325_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ca9638a0-0347-4015-816d-bfff96830a1c)

**Comment by toirehantaa** [comment]
should be fixed now, china supply able to be built everywhere on the supply crates between the players

**Comment by xezon** [comment]
Yes, looks good.
