### ISSUE TITLE
[Candidate 1v1 Salt Lake River ZH v2] Audio emitters do not ease in and out well

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#664]
## Observed behavior

Audio emitters do not ease in and out well. Especially the talking people at the huts are not optimal.

## Expected behavior

Auto emitters ease in and out well.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7b77d8c8-31fb-43f9-b4a5-b2ae95b4e0e1

**Comment by NoMerciBKK** [comment]
fixed

**Comment by xezon** [comment]
The talking people by the huts still do not ease well. Can you double check?

**Comment by NoMerciBKK** [comment]
> The talking people by the huts still do not ease well. Can you double check?

should be fixed now

**Comment by xezon** [comment]
Is better on most, but there is still one left not optimal:

![shot_20240426_202842_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/832d80e2-cb31-4a96-a913-f775f2259cb5)
