### ISSUE TITLE
[Candidate 4v4 Battle Between Them ZH v5] Bunkers barely shoot backwards or not at all

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#723]
## Observed behavior

Bunkers barely shoot backwards or not at all.

## Expected behavior

Bunkers can shoot backwards.

### Just 1 of 10 Soldiers shoots backwards (at least 3)

![shot_20240509_121052_21](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e488f6d8-958b-4564-93a3-893488f9beb8)

![shot_20240509_121126_23](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bc52b3c8-2a59-44e4-9133-287518e4eab0)

![shot_20240509_121239_24](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0d00c776-75c5-4bdc-9923-a227bd99e7e5)

### None of 10 Soldiers shoots backwards (at least 2)

![shot_20240509_121324_26](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b14654c7-3e8b-4104-b24a-36f6f8d025c6)

![shot_20240509_121532_28](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8ad18410-fa87-4fbc-a743-e9c634556b94)

**Comment by xezon** [comment]
Likely can be fixed by raising bunkers.

* See also #722

**Comment by NoMerciBKK** [comment]
fixed

**Comment by xezon** [comment]
Is not fixed.

So for example on this bunker, soldiers can shoot backwards quite massively:

![shot_20240510_160218_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/22346483-ad6c-4ed2-b118-8f21379cdaf2)

But another bunker has trouble shooting sideways and backwards:

![shot_20240510_160253_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c583f766-f94b-47cf-ae96-29c777ea405d)
![shot_20240510_160300_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8806caf2-ae5c-4e4d-b4af-c90a30369380)
![shot_20240510_160316_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ee2042d4-5e04-4a86-a3a9-95e0fef7b4a0)

I suspect this fails because terrain is ever so slightly different.
